email_address:
  name: Email Address
  type: string
  default: example@example.com

email_name:
  default: Site Administrator
  type: string
  
password:
  default: password
  type: password
  name: Password
  
description:
  default: My Awesome Site
  type: text
  name: Description
  
value:
  default: "10"
  type: integer
  name: Value
  
price:
  default: "10.00"
  type: decimal
  name: Price
  
options:
  name: Select Options
  default: 1
  type: select
  options:
    - [ One, 1 ]
    - [ Two, 2 ]
    - [ Three, 3 ]