email_address:
  name: Email Address
  type: string
  default: example@example.com

email_name:
  default: Site Administrator
  type: string
  name: Email Name
  
password:
  default: password
  type: password
  name: Password
  
description:
  default: My Awesome Site
  type: text
  name: Description